apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-web
  labels:
    app: events-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-web
  template:
    metadata:
      labels:
        app: events-web
    spec:
      containers:
        name: events-web
        image: jayrajendran123/market-app-ext:v1.0.0
        env:
          name: PORT
          value: "8888"
          name: SERVER
          value: "http://events-data-service"
        ports:
          containerPort: 8888
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.1"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 60

apiVersion: v1
kind: Service
metadata: 
  name: events-web-service
spec: 
  ports: 
     -  port: 8888
        protocol: TCP
        targetPort: 8888
  selector: 
    app: events-web
  type: LoadBalancer